name: doc_scan_kit
description: "Flutter plugin that performs document scanning, using ML Kit on Android and Vision Kit on iOS"
version: 0.0.7
homepage: https://github.com/rajada1/doc_scan_kit

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.rajada1_docscan_kit.doc_scan_kit
        pluginClass: DocScanKitPlugin
      ios:
        pluginClass: DocScanKitPlugin
